spring:
  app:
    jwtSecret: cXdlcnR5dWlvcGxramhnZHNhYXNkZmdoYm52Y3h6eGNhc2RmZ2hoanJyZXdlcnR5dWp1bmN4Y3ZiamhnZmVkZnZnYmhkZmQ=
    jwtExpirationMs: 5000000
    jwtCookie: springbootEcom
  application:
    name: eCommerce-App
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    properties:
          hibernate:
            ddl-auto: update
            format_sql: true
product:
  image: "images/"

logging:
  level:
    com:
      richardvinz.eCommerce_App: DEBUG
    org:
      springframework: DEBUG
      security: DEBUG
      hibernate:
        sql: DEBUG
